[build]
  command = "npm run build"
  publish = ".next"
[[redirects]]
  from = "/my-trees"
  to = "/login"
  status = 301
  force = false
[[redirects]]
  from = "/redeem"
  to = "/login"
  status = 301
  force = false
[[redirects]]
  from = "/yucatan-reforestation"
  to = "/yucatan"
  status = 301
  force = false
[[plugins]]
  package = "@netlify/plugin-nextjs"
